# Chicago Food Inspections Data Preprocessing

In [49]:
import pandas as pd
import numpy as np

In [5]:
main_df = pd.read_csv('/Users/showhq/Project_ChicagoFoodInspections/ChicagoFoodInspections.csv')

In [11]:
main_df

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
0,2621936,SHEPHERD SUPERMARKET INC,SHEPHERD SUPERMARKET INC,3041503.0,NaN,NaN,2532 W 63RD ST,CHICAGO,IL,60629.0,08/08/2025,License,Not Ready,NaN,41.779313,-87.687371,"(41.779312917689595, -87.68737071929175)"
1,2621957,JACK IN THE BOX #4220,JACK IN THE BOX,3025373.0,Restaurant,Risk 2 (Medium),7807 S CICERO AVE,CHICAGO,IL,60652.0,08/08/2025,License,Pass,NaN,41.750727,-87.741269,"(41.75072749003623, -87.74126860209364)"
2,2621940,LITTLE ANGELS LEARNING CENTER,LITTLE ANGELS LEARNNG CENTER CORPORATION,2583933.0,Daycare Above and Under 2 Years,Risk 1 (High),6900-6908 S PULASKI RD,CHICAGO,IL,60629.0,08/08/2025,License,Pass,36. THERMOMETERS PROVIDED & ACCURATE - Comment...,41.767688,-87.722631,"(41.767687732304424, -87.72263084508015)"
3,2621894,BWW GO,BWW GO,3036907.0,Restaurant,Risk 1 (High),3415 W IRVING PARK RD,CHICAGO,IL,60618.0,08/07/2025,License,Pass,NaN,41.953738,-87.713554,"(41.95373772554195, -87.71355424156796)"
4,2621887,BACCI PIZZERIA ON CHICAGO AVE,BACCI PIZZERIA,1647808.0,Restaurant,Risk 1 (High),2343 W CHICAGO AVE,CHICAGO,IL,60622.0,08/07/2025,Canvass Re-Inspection,Pass,"38. INSECTS, RODENTS, & ANIMALS NOT PRESENT - ...",41.895645,-87.686110,"(41.89564503175785, -87.68610988884953)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295015,70269,mr.daniel's,mr.daniel's,1899292.0,Restaurant,Risk 1 (High),5645 W BELMONT AVE,CHICAGO,IL,60634.0,01/04/2010,License Re-Inspection,Pass,NaN,41.938443,-87.768318,"(41.93844282365204, -87.76831838068422)"
295016,52234,Cafe 608,Cafe 608,2013328.0,Restaurant,Risk 1 (High),608 W BARRY AVE,CHICAGO,IL,60657.0,01/04/2010,License Re-Inspection,Pass,NaN,41.938007,-87.644755,"(41.938006880423615, -87.6447545707008)"
295017,67733,WOLCOTT'S,TROQUET,1992040.0,Restaurant,Risk 1 (High),1834 W MONTROSE AVE,CHICAGO,IL,60613.0,01/04/2010,License Re-Inspection,Pass,NaN,41.961606,-87.675967,"(41.961605669949854, -87.67596676683779)"
295018,67738,MICHAEL'S ON MAIN CAFE,MICHAEL'S ON MAIN CAFE,2008948.0,Restaurant,Risk 1 (High),8750 W BRYN WAWR AVE,CHICAGO,IL,60631.0,01/04/2010,License,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,NaN,NaN,NaN
295019,104236,TEMPO CAFE,TEMPO CAFE,80916.0,Restaurant,Risk 1 (High),6 E CHESTNUT ST,CHICAGO,IL,60611.0,01/04/2010,Canvass,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,41.898431,-87.628009,"(41.89843137207629, -87.6280091630558)"

In [13]:
main_df.columns

Index(['Inspection ID', 'DBA Name', 'AKA Name', 'License #', 'Facility Type',
       'Risk', 'Address', 'City', 'State', 'Zip', 'Inspection Date',
       'Inspection Type', 'Results', 'Violations', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [15]:
main_df.dtypes

Inspection ID        int64
DBA Name            object
AKA Name            object
License #          float64
Facility Type       object
Risk                object
Address             object
City                object
State               object
Zip                float64
Inspection Date     object
Inspection Type     object
Results             object
Violations          object
Latitude           float64
Longitude          float64
Location            object
dtype: object

**General Cleaning, Converting Data Types:**

In [29]:
main_df.columns=(main_df.columns.str.strip().str.lower().str.replace(r'[^a-z0-9]+','_',regex=True).str.strip('_'))
main_df.head(1)

,inspection_id,dba_name,aka_name,license,facility_type,risk,address,city,state,zip,inspection_date,inspection_type,results,violations,latitude,longitude,location
0,2621936,SHEPHERD SUPERMARKET INC,SHEPHERD SUPERMARKET INC,3041503.0,<NA>,<NA>,2532 W 63RD ST,CHICAGO,IL,60629,2025-08-08,License,Not Ready,<NA>,41.779313,-87.687371,"(41.779312917689595, -87.68737071929175)"

In [31]:
main_df.columns

Index(['inspection_id', 'dba_name', 'aka_name', 'license', 'facility_type',
       'risk', 'address', 'city', 'state', 'zip', 'inspection_date',
       'inspection_type', 'results', 'violations', 'latitude', 'longitude',
       'location'],
      dtype='object')

In [39]:
text_cols=['dba_name','aka_name','facility_type','risk','address','city','state','inspection_type','results','violations','location']
main_df[text_cols]=main_df[text_cols].astype('string').apply(lambda s:s.str.strip())

text_cols = ['dba_name','aka_name','facility_type','risk','address','city','state',
             'inspection_type','results','violations','location']
main_df[text_cols] = main_df[text_cols].astype('string').apply(lambda s: s.str.strip())

main_df['inspection_date'] = pd.to_datetime(main_df['inspection_date'], errors='coerce')
main_df['license'] = pd.to_numeric(main_df['license'], errors='coerce').astype('Int64')
main_df['zip'] = main_df['zip'].astype('string').str.extract(r'(\d{5})')[0]
main_df['latitude'] = pd.to_numeric(main_df['latitude'], errors='coerce')
main_df['longitude'] = pd.to_numeric(main_df['longitude'], errors='coerce')
main_df[text_cols + ['zip']] = main_df[text_cols + ['zip']].fillna('_')

In [45]:
main_df.head(3)

,inspection_id,dba_name,aka_name,license,facility_type,risk,address,city,state,zip,inspection_date,inspection_type,results,violations,latitude,longitude,location
0,2621936,SHEPHERD SUPERMARKET INC,SHEPHERD SUPERMARKET INC,3041503,_,_,2532 W 63RD ST,CHICAGO,IL,60629,2025-08-08,License,Not Ready,_,41.779313,-87.687371,"(41.779312917689595, -87.68737071929175)"
1,2621957,JACK IN THE BOX #4220,JACK IN THE BOX,3025373,Restaurant,Risk 2 (Medium),7807 S CICERO AVE,CHICAGO,IL,60652,2025-08-08,License,Pass,_,41.750727,-87.741269,"(41.75072749003623, -87.74126860209364)"
2,2621940,LITTLE ANGELS LEARNING CENTER,LITTLE ANGELS LEARNNG CENTER CORPORATION,2583933,Daycare Above and Under 2 Years,Risk 1 (High),6900-6908 S PULASKI RD,CHICAGO,IL,60629,2025-08-08,License,Pass,36. THERMOMETERS PROVIDED & ACCURATE - Comment...,41.767688,-87.722631,"(41.767687732304424, -87.72263084508015)"

In [40]:
main_df.to_csv('main_CHI_Food_Inspection.csv',index=False)

In [53]:
main_df['year'] = main_df['inspection_date'].dt.year
main_df['month'] = main_df['inspection_date'].dt.month
main_df['month_name'] = main_df['inspection_date'].dt.month_name()
main_df['year_month'] = main_df['inspection_date'].dt.to_period('M').astype(str)

**Time Fields:**

In [ ]:
main_df['year'] = main_df['inspection_date'].dt.year
main_df['month'] = main_df['inspection_date'].dt.month
main_df['month_name'] = main_df['inspection_date'].dt.month_name()
main_df['year_month'] = main_df['inspection_date'].dt.to_period('M').astype(str)

**Normalized Categories:**

In [63]:
results_col = main_df['results'].str.lower()
main_df['results_norm'] = np.select(
    [results_col.eq('pass') | results_col.eq('passed'),
     results_col.str.contains('cond', na=False),
     results_col.str.contains('fail', na=False)],
    ['Pass','Conditional Pass','Fail'],
    'Other'
)
risk_col = main_df['risk'].str.lower()
main_df['risk_norm'] = np.select(
    [risk_col.str.startswith('risk 1') | risk_col.str.contains('high', na=False),
     risk_col.str.startswith('risk 2') | risk_col.str.contains('medium', na=False),
     risk_col.str.startswith('risk 3') | risk_col.str.contains('low', na=False)],
    ['High','Medium','Low'],
    '_'
)

**Violations Features:**

In [67]:
violations_col = main_df['violations'].fillna('').astype(str).str.strip()
violations_col = violations_col.str.replace(';','|').str.replace(',','|')
main_df['violations_count'] = np.where(
    violations_col.eq(''), 0, violations_col.str.split('|').apply(lambda L: len([x for x in L if x.strip()]))
)

In [69]:
def extract_first_violation_code(violation_entry):
    if not isinstance(violation_entry, str) or not violation_entry.strip():
        return '_'
    for token in violation_entry.split():
        token_lower = token.lower()
        if token_lower.startswith('code') or token[:1].isdigit():
            return token.title()
    return '_'

In [71]:
main_df['top_violation_code'] = main_df['violations'].apply(extract_first_violation_code)

**Outcomes & Cadence:**

In [75]:
main_df['pass_flag'] = main_df['results_norm'].isin(['Pass','Conditional Pass']).astype('int8')
main_df['fail_flag'] = main_df['results_norm'].eq('Fail').astype('int8')

In [77]:
main_df = main_df.sort_values(['license','inspection_date'])
main_df['days_since_prev'] = (main_df.groupby('license', dropna=False)['inspection_date'].diff().dt.days)

In [79]:
main_df.to_csv('chicago_food_inspections.csv', index=False)